### ISSUE TITLE
water temperature module in water quality simulation

### ISSUE THREAD

**Issue by mengfeimu** [djlampert/PyHSPF#3]
Hi Dr. Lampert,

Thanks for developing so useful tools for HSPF community. I am planning to use HSPF to simulate the streamflow and **river water temperature**. However, I see you said in [wishlist.md](https://github.com/djlampert/PyHSPF/blob/master/wishlist.md) that the addition of HSPF temperature module is left to the future. This confuses me because I thought PyHSPF complies every module from original HSPF to python. 

My concern is: does the water temperature module work in the current version of PyHSPF? This is important for me because I have to use original HSPF if temperature module is not included in the current PyHSPF.

Thanks for your reply!

**Comment by djlampert** [comment]
Hi Meng Fei Mu! So you can definitely still use the HSPF stream temperature tools, but there isn't currently any Python support to import the data for that module or auto generate the input files. I expect that it wouldn't be difficult to add though--and it would be the next priority. When I am done with the semester in 1 month, I plan to update everything. You might check back with me then if you have questions.
