### ISSUE TITLE
Compilation on linux

### ISSUE THREAD

**Issue by taataam** [djlampert/PyHSPF#8]
I tried to compile the code on Ubuntu 18.04 with python3 but get the following error:

```bash
$ python3 setup.py config --compiler=gcc build --compiler=gcc
...
...
build_src: building npy-pkg config files
running build_py
running build_ext
error: don't know how to compile C/C++ code on platform 'posix' with 'gcc' compiler
```

I installed the prerequisites using apt and am not using Anaconda.

**Comment by djlampert** [comment]
I have not seen this problem before. Can you try just compiling the "C" files in the src/hspf13 directory without python from the command line?

**Comment by taataam** [comment]
It seems to be compiled as expected. I attached the log:
[gcc.log](https://github.com/djlampert/PyHSPF/files/2818268/gcc.log)

**Comment by djlampert** [comment]
The log says it error. Can you successful compile the four c files into objects? gcc -c *.o?

**Comment by djlampert** [comment]
I don't think you need to specify the compiler flags on linux. It should be pretty straightforward...python3 setup.py build then sudo python3 setup.py install. The other instructions are for windows. If this works for you, I will try to update the readme to clarify.

**Comment by taataam** [comment]
I tried it without the compiler flag as you mentioned but gives the following error:
```bash
....
No module named 'numpy.distutils.cygwinccompiler' in numpy.distutils; trying from distutils
....
```

I attached the log. I think use of this module is hardcoded so it cannot use a compiler based on the OS.
[noflag.log](https://github.com/djlampert/PyHSPF/files/2822066/noflag.log)

**Comment by taataam** [comment]
I was looking at the setup.py and have a minor suggestion, line 145:
```python
files = ['hspf13/{}'.format(f)
         for f in os.listdir('hspf13')
         if f[-1] == 'c' or f[-1] == 'f']
```
can be replaced by:
```python
files = glob.glob('hspf13/*.[c,f]')
```

**Comment by taataam** [comment]
I just saw your gcc comment. Yes, I can successfully compile with ``` gcc -c *.c``` without any error.

**Comment by wk1984** [comment]
Try: 
`python3 setup.py config --compiler=unix build --compiler=unix`
It seems like to work with default gcc and gfortran compiler.

**Comment by taataam** [comment]
It worked. Thanks. Also, I had to add a user flag to avoid "permission denied":
```bash
$> python3 setup.py config --compiler=unix build --compiler=unix install  --user
```

**Comment by djlampert** [comment]
Great to hear. I am going to go ahead and close this issue then. Thank you Kong, and I hope you both are getting some value from this effort!

**Comment by abhiramp1** [comment]
If anyone is still trying to install pyhspf in their linux systems, you need to delete config file and then build using command **python3 setup.py build**. After building install pyhspf by $python3 setup.py install$
